Добавляет имя наставника
htmlacademy-javascript/2119997-keksobooking-27 pull request #1
Opened 2022-09-29 18:41 UTC by MetlikGG

2022-09-30 18:09 UTC, GennadiyM requested changes

2022-09-30 18:09 UTC, GennadiyM commented on Readme.md
> +* Наставник: `Геннадий Максимов`.
запись должна быть того же формата что и твои данные. В квадратных скобках имя фамилия, в круглых ссылка на мой профиль в академии. Файл readme явяется документом к проекту и должен заполняться согласно определенным правилам

2022-09-30 18:09 UTC, GennadiyM commented on js/main.js
> +
зачем было создавать файл, если он никуда не подключен и в нем ничего нет. Следи за "мусором" в пул реквесте

2022-10-01 11:09 UTC, MetlikGG commented on Readme.md
> +* Наставник: `Геннадий Максимов`.
Исправил файл readme. main.js был в проекте, я проверял eslint, пока удалил main.js.

2022-10-01 22:50 UTC, GennadiyM approved these changes

2022-10-01 22:50 UTC, merged