Правда или действие (часть 1)
htmlacademy-javascript/2119997-keksobooking-27 pull request #7
Opened 2022-10-28 12:50 UTC by MetlikGG

---
:mortar_board: [Правда или действие (часть 1)](https://up.htmlacademy.ru/javascript/27/user/2119997/tasks/14)

2022-10-29 12:15 UTC, GennadiyM requested changes

2022-10-29 12:15 UTC, GennadiyM commented on js/validation-form.js
> +const TITLE_SIZES = {
TitleSizes

2022-10-29 12:15 UTC, GennadiyM commented on js/validation-form.js
> +  min: 30,
MIN

2022-10-29 12:15 UTC, GennadiyM commented on js/validation-form.js
> +  min: 0,
MIN

2022-10-29 12:15 UTC, GennadiyM commented on js/validation-form.js
> +const validateTitle = (value) => value.length >= TITLE_SIZES.min && value.length <= TITLE_SIZES.max;
проверь не было ли у тебя в утилитах похожей функции

2022-10-29 12:15 UTC, GennadiyM commented on js/validation-form.js
> +};
У тебя условия пересекаются, в обоих есть либо равно

2022-10-29 12:15 UTC, GennadiyM commented on js/validation-form.js
> +  }
У тебя условия пересекаются, в обоих есть либо равно

2022-10-30 16:32 UTC, MetlikGG commented on js/validation-form.js
> +const validateTitle = (value) => value.length >= TITLE_SIZES.min && value.length <= TITLE_SIZES.max;
Не нашёл

2022-10-31 08:14 UTC, GennadiyM approved these changes

2022-10-31 08:14 UTC, merged